language: python
cache: pip

matrix:
  include:
    - env: TOXENV=py27-dj111-wag113
      python: 2.7
    - env: TOXENV=py36-dj111-wag113
      python: 3.6
    - env: TOXENV=py36-dj111-wag20
      python: 3.6
    - env: TOXENV=py36-dj20-wag20
      python: 3.6
    - env: TOXENV=py36-dj20-wag24
      python: 3.6
    - env: TOXENV=py36-dj20-wag25
      python: 3.6
    - env: TOXENV=py36-dj21-wag24
      python: 3.6
    - env: TOXENV=py36-dj22-wag25
      python: 3.6
    - env: TOXENV=flake8
      python: 3.6

install:
  pip install tox

script:
  tox
